oe_content_event.event_profile_type.*:
  type: config_entity
  label: 'Event Profile Type settings'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
