<?php

/**
 * @file
 * The OpenEuropa Content Event module.
 */

declare(strict_types = 1);

use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_entity_type_alter().
 */
function oe_content_event_entity_type_alter(array &$entity_types) {
  // Add validation constraints to the node entity.
  $entity_types['node']->addConstraint('EventFieldsRequired');
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function oe_content_event_form_node_oe_event_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Add a toggle switch for "Organiser" fields.
  $form['is_organiser_internal'] = [
    '#type' => 'checkbox',
    '#title' => t('Organiser is internal'),
    '#default_value' => $form_state->getValue('field_organiser_internal') ? 1 : 0,
  ];
  $form['field_organiser_internal']['#states'] = [
    'visible' => [
      ':input[name="is_organiser_internal"]' => ['checked' => TRUE],
    ],
  ];
  $form['field_organiser_name']['#states'] = [
    'visible' => [
      ':input[name="is_organiser_internal"]' => ['checked' => FALSE],
    ],
  ];

  // Make sure that the toggle field we have just created
  // will be rendered under the "Organiser" field group.
  $group_id = 'group_organiser';
  $organiser_group = $form['#fieldgroups'][$group_id];
  $organiser_group->children[] = 'is_organiser_internal';
  $form['#fieldgroups'][$group_id] = $organiser_group;
  $form['#group_children']['is_organiser_internal'] = $group_id;
}

/**
 * Field default value callback.
 *
 * @param \Drupal\Core\Entity\FieldableEntityInterface $entity
 *   The entity being created.
 * @param \Drupal\Core\Field\FieldDefinitionInterface $definition
 *   The field definition.
 *
 * @return array
 *   An array of default values, in the same format as the $default_value
 *   property.
 */
function oe_event_field_default_value(FieldableEntityInterface $entity, FieldDefinitionInterface $definition): array {
  $return = [];

  if ($definition->getName() === 'field_description_title') {
    $return[] = t('Description');
  }

  if ($definition->getName() === 'field_report_title') {
    $return[] = t('Report');
  }

  return $return;
}
