<?php

/**
 * @file
 * The module file.
 */

declare(strict_types = 1);

/**
 * Implements hook_theme().
 */
function oe_content_entity_contact_theme() {
  return [
    'oe_contact' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function template_preprocess_oe_contact(array &$variables) {
  oe_content_entity_default_preprocess($variables, 'oe_contact');
}
