clone:
  git:
    image: registry.fpfis.eu/drone-plugins/git:next
    when:
      event: [ push, pull_request, tag ]
  git:
    image: registry.fpfis.eu/drone-plugins/git
    when:
      event: [ deployment ]

workspace:
  base: /test
  path: oe_content

services:
  web:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    environment:
      - COMPOSERVER=--2
      - DOCUMENT_ROOT=/test/oe_content
  mysql:
    image: registry.fpfis.eu/fpfis/sql:percona-5.7
    command: --innodb-log-file-size=1G --max_allowed_packet=1G --innodb-buffer-pool-size=512M --wait_timeout=3000 --net_write_timeout=3000 --log_error_verbosity=3
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  sparql:
    image: openeuropa/triple-store-dev
    pull: true
    environment:
      - SPARQL_UPDATE=true
      - DBA_PASSWORD=dba
  selenium:
    image: registry.fpfis.eu/fpfis/selenium:standalone-chrome-3.141.59-oxygen
    pull: true
    shm_size: 2g
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug
      - SCREEN_WIDTH=1280
      - SCREEN_HEIGHT=800
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5

pipeline:
  composer-add-lenient:
    group: warmup
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    commands:
      # Pre-install 9.4.x so that all modules are compatible and plugins are installed too.
      - composer require drupal/core:~9.4.0 drupal/core-composer-scaffold:~9.4.0 --update-with-all-dependencies --ansi --no-progress --no-interaction --no-plugins --no-scripts
      # Install the lenient plugin so that non-D10 ready components will be marked as compatible.
      - composer require mglaman/composer-drupal-lenient --ansi --no-progress --no-interaction --no-plugins --no-scripts
      # Delete the lock file to ignore all dependencies when requiring D10.
      - rm -f composer.lock
    when:
      matrix:
        CORE_VERSION: "10.0"

  composer-install:
    group: prepare
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    commands:
      - composer require drupal/core:~${CORE_VERSION} drupal/core-composer-scaffold:~${CORE_VERSION} --update-with-all-dependencies --ansi --no-progress --no-interaction

  site-install:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - while ! mysqladmin ping -h mysql --silent; do sleep 1; done
      - ./vendor/bin/run drupal:site-install
      - ./vendor/bin/drush en -y oe_countries_test
    when:
      matrix:
        TYPE: behat

  grumphp:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/grumphp run
    when:
      matrix:
        COMPOSER_BOUNDARY: highest
        TYPE: phpunit

  phpunit:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/phpunit
    when:
      matrix:
        TYPE: phpunit

  # Ensure that all Behat scenarios have been tagged with a batch tag.
  ensure-behat-batching:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/run behat:ensure-batching --path $(pwd)/tests/features
    when:
      matrix:
        TYPE: phpunit

  behat:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/behat --strict --tags=$BATCH
    when:
      matrix:
        TYPE: behat

  debug:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/drush ws --count 500
    when:
      status: failure
      matrix:
        TYPE: behat

matrix:
  include:
    - { PHP_VERSION: 8.0, CORE_VERSION: 9.4.0, TYPE: phpunit }
    - { PHP_VERSION: 8.0, CORE_VERSION: 9.4.0, TYPE: behat, BATCH: '@batch1' }
    - { PHP_VERSION: 8.0, CORE_VERSION: 9.4.0, TYPE: behat, BATCH: '@batch2' }
    - { PHP_VERSION: 8.0, CORE_VERSION: 9.4.0, TYPE: behat, BATCH: '@batch3' }

    - { PHP_VERSION: 8.1, CORE_VERSION: 9.4.0, TYPE: phpunit }
    - { PHP_VERSION: 8.1, CORE_VERSION: 9.4.0, TYPE: behat, BATCH: '@batch1' }
    - { PHP_VERSION: 8.1, CORE_VERSION: 9.4.0, TYPE: behat, BATCH: '@batch2' }
    - { PHP_VERSION: 8.1, CORE_VERSION: 9.4.0, TYPE: behat, BATCH: '@batch3' }

    - { PHP_VERSION: 8.1, CORE_VERSION: 10.0, TYPE: phpunit }
    - { PHP_VERSION: 8.1, CORE_VERSION: 10.0, TYPE: behat, BATCH: '@batch1' }
    - { PHP_VERSION: 8.1, CORE_VERSION: 10.0, TYPE: behat, BATCH: '@batch2' }
    - { PHP_VERSION: 8.1, CORE_VERSION: 10.0, TYPE: behat, BATCH: '@batch3' }
