<?php

/**
 * @file
 * The OpenEuropa Content module.
 */

declare(strict_types=1);

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\oe_content\Hook\OeContentHooks;

/**
 * Implements hook_entity_base_field_info().
 *
 * Drupal 11.1 introduced support for object-oriented hook implementations.
 * See: https://www.drupal.org/node/3442349
 *
 * The changes in hook management introduced a new issue: in some contexts
 * module hooks are not registered correctly.
 * See: https://www.drupal.org/project/drupal/issues/3502302
 * Due to this issue the oe_content_entity_base_field_info hook is not
 * registered correctly in D11.1 using the old procedural hook implementation.
 * Note: reason is a collision with the name of oe_content_entity submodule.
 *
 * As the issue doesn't have a fix yet, the workaround is to use the new OOP
 * hook implementation for this hook that can be implemented in a backward
 * compatible way for Drupal versions 10.1 to 11.0.
 * The purpose of this legacy hook is to achieve backward compatibility for
 * Drupal versions lower than 11.1.
 *
 * Also see the 'Drupal\oe_content\Hook\OeContentHooks' service in
 * oe_content.services.yml (also added for backward compatibility).
 *
 * @todo Remove when core versions lower than 11.1 are not supported anymore.
 *
 * @see \Drupal\oe_content\Hook\OeContentHooks
 */
#[LegacyHook]
function oe_content_entity_base_field_info(EntityTypeInterface $entity_type): array {
  return \Drupal::service(OeContentHooks::class)->entityBaseFieldInfo($entity_type);
}

/**
 * Implements hook_locale_translation_projects_alter().
 */
function oe_content_locale_translation_projects_alter(&$projects) {
  $projects['oe_content']['info']['interface translation server pattern'] = \Drupal::service('extension.list.module')->getPath('oe_content') . '/translations/%project-%language.po';
}

/**
 * Implements hook_ENTITY_TYPE_prepare_form().
 */
function oe_content_node_prepare_form(EntityInterface $entity, $operation, FormStateInterface $form_state) {
  /** @var \Drupal\node\NodeInterface $entity */
  if ($entity->isNew() === FALSE) {
    return;
  }

  if ($entity->hasField('oe_content_content_owner') === FALSE) {
    return;
  }

  if (\Drupal::service('module_handler')->moduleExists('oe_corporate_site_info') === FALSE) {
    return;
  }

  /** @var \Drupal\oe_corporate_site_info\SiteInformationInterface $site_information */
  $site_information = \Drupal::service('oe_corporate_site_info.site_information');
  if (!$site_information->hasDefaultContentOwners()) {
    // No content owner(s) defined.
    return;
  }
  $content_owners = $site_information->getDefaultContentOwners();
  $entity->set('oe_content_content_owner', array_values($content_owners));
}

/**
 * Implements hook_theme().
 */
function oe_content_theme() {
  return [
    'collapsible_actions' => [
      'render element' => 'element',
      'template' => 'collapsible-actions',
    ],
  ];
}

/**
 * Prepares variables for the collapsible_actions component.
 *
 * Default template: collapsible-actions.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - actions: An array of default action buttons.
 *   - dropdown_actions: An array of buttons for dropdown.
 */
function template_preprocess_collapsible_actions(&$variables) {
  // Define variables for the template.
  $variables += ['actions' => [], 'dropdown_actions' => []];

  $element = $variables['element'];

  if (!empty($element['actions'])) {
    $variables['actions'] = $element['actions'];
  }

  if (!empty($element['dropdown_actions'])) {
    $variables['dropdown_actions'] = $element['dropdown_actions'];
  }
}

/**
 * Implements hook_preprocess_HOOK() for field_multiple_value_form().
 */
function oe_content_preprocess_field_multiple_value_form(&$variables) {
  if (!empty($variables['table']['#header']) && isset($variables['table']['#rows'][0])) {
    // Find collapsible_actions and move to header.
    // @see template_preprocess_field_multiple_value_form()
    if (is_array($variables['table']['#rows'][0]['data'][1]) && !empty($variables['table']['#rows'][0]['data'][1]['data']['#field_header'])) {
      $variables['table']['#header'][1]['data'] = [
        $variables['table']['#rows'][0]['data'][1]['data'],
      ];
      unset($variables['table']['#rows'][0]);
    }
  }
}
