<?php

/**
 * @file
 * The OpenEuropa Content module.
 */

declare(strict_types = 1);

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_locale_translation_projects_alter().
 */
function oe_content_locale_translation_projects_alter(&$projects) {
  $projects['oe_content']['info']['interface translation server pattern'] = drupal_get_path('module', 'oe_content') . '/translations/%project-%language.po';
}

/**
 * Implements hook_ENTITY_TYPE_prepare_form().
 */
function oe_content_node_prepare_form(EntityInterface $entity, $operation, FormStateInterface $form_state) {
  /** @var \Drupal\node\NodeInterface $entity */
  if ($entity->isNew() === FALSE) {
    return;
  }

  if ($entity->hasField('oe_content_content_owner') === FALSE) {
    return;
  }

  if (\Drupal::service('module_handler')->moduleExists('oe_corporate_site_info') === FALSE) {
    return;
  }

  /** @var \Drupal\oe_corporate_site_info\SiteInformationInterface $site_information */
  $site_information = \Drupal::service('oe_corporate_site_info.site_information');
  if (!$site_information->hasDefaultContentOwners()) {
    // No content owner(s) defined.
    return;
  }
  $content_owners = $site_information->getDefaultContentOwners();
  $entity->set('oe_content_content_owner', array_values($content_owners));
}
