<?php

declare(strict_types = 1);

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function oe_timeline_test_constraint_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  // Add constraint to the paragraphs field of the Timeline paragraph.
  if ($entity_type->id() === 'node') {
    if (isset($fields['timeline'])) {
      $fields['timeline']->addConstraint('oe_timeline_test_constraint', []);
    }
  }
}
