oe_content_entity_organisation.oe_organisation_type.*:
  type: config_entity
  label: 'Organisation Type settings'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
