<?php

/**
 * @file
 * Primary module hooks for OpenEuropa Project content module.
 */

declare(strict_types=1);

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_field_widget_single_element_WIDGET_TYPE_form_alter().
 */
function oe_content_project_field_widget_single_element_number_form_alter(array &$element, FormStateInterface $form_state, array $context) {
  $field_definition = $context['items']->getFieldDefinition();

  // Workaround for https://www.drupal.org/project/drupal/issues/2230909.
  if (!in_array($field_definition->getName(), ['oe_project_eu_budget', 'oe_project_eu_contrib'])) {
    return;
  }

  $element['value']['#step'] = '0.01';
}
