<?php

/**
 * @file
 * The OpenEuropa Content Timeline Field module.
 */

declare(strict_types = 1);

/**
 * Implements hook_theme().
 */
function oe_content_timeline_field_theme() {
  return [
    'timeline' => [
      'variables' => [
        'limit' => 0,
        'show_more' => t('Show full timeline'),
        'items' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_locale_translation_projects_alter().
 */
function oe_content_timeline_field_locale_translation_projects_alter(&$projects) {
  $projects['oe_content_timeline_field']['info']['interface translation server pattern'] = \Drupal::service('extension.list.module')->getPath('oe_content_timeline_field') . '/translations/%project-%language.po';
}

/**
 * Implements hook_field_info_alter().
 */
function oe_content_timeline_field_field_info_alter(&$info) {
  if (isset($info['timeline_field'])) {
    // For the timeline_field field we need to use our own field processor
    // depending on the translation service used (TMGMT or oe_translation).
    if (class_exists('\Drupal\oe_translation\TranslationSourceFieldProcessor\DefaultFieldProcessor')) {
      $info['timeline_field']['oe_translation_source_field_processor'] = 'Drupal\oe_content_timeline_field\TimelineFieldProcessor';
    }
    else {
      $info['timeline_field']['tmgmt_field_processor'] = 'Drupal\oe_content_timeline_field\TimelineFieldProcessor';
    }
  }
}
