<?php

/**
 * @file
 * The OpenEuropa Content Timeline Field module.
 */

declare(strict_types = 1);

/**
 * Implements hook_theme().
 */
function oe_content_timeline_field_theme() {
  return [
    'timeline' => [
      'variables' => [
        'limit' => 0,
        'show_more' => t('Show full timeline'),
        'items' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_locale_translation_projects_alter().
 */
function oe_content_timeline_field_locale_translation_projects_alter(&$projects) {
  $projects['oe_content_timeline_field']['info']['interface translation server pattern'] = drupal_get_path('module', 'oe_content_timeline_field') . '/translations/%project-%language.po';
}
