<?php

/**
 * @file
 * The module file.
 */

declare(strict_types = 1);

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function oe_content_entity_theme() {
  return [
    'oe_content_entity' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Default preprocess function to be ran for all corporate entities.
 *
 * This preprocess sets default values to be passed to the main entity
 * render template.
 *
 * @param array $variables
 *   Render variables.
 */
function template_preprocess_oe_content_entity(array &$variables) {
  $variables['entity'] = $variables['elements']["#{$variables['theme_hook_original']}"];
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  $variables['label'] = $variables['entity']->label();

  // Helpful $content variable for templates.
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
