<?php

/**
 * @file
 * The module file.
 */

declare(strict_types = 1);

use Drupal\Core\Render\Element;

/**
 * Default preprocess function to be ran for all corporate entities.
 *
 * This preprocess sets default values to be passed to the main entity
 * render template.
 *
 * @param array $variables
 *   Render variables.
 * @param string $hook
 *   Hook name, in this case the entity type ID itself.
 */
function oe_content_entity_default_preprocess(array &$variables, string $hook) {
  $variables['entity'] = $variables['elements']["#{$hook}"];
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  $variables['label'] = $variables['entity']->label();

  // Helpful $content variable for templates.
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
