<?php

/**
 * @file
 * Install, update and uninstall functions.
 */

declare(strict_types=1);

use Drupal\oe_content\ConfigImporter;

/**
 * Implements hook_install().
 */
function oe_content_publication_document_reference_install($is_syncing): void {
  if ($is_syncing) {
    return;
  }

  $extension = 'oe_content_publication_document_reference';
  $config_path = '/tasks/install';

  if (\Drupal::moduleHandler()->moduleExists('content_translation')) {
    ConfigImporter::importSingle('module', $extension, $config_path, 'language.content_settings.oe_document_reference.oe_publication');
  }
}
