oe_content_entity_contact.oe_contact_type.*:
  type: config_entity
  label: 'Contact Type settings'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
