<?php

/**
 * @file
 * The module file.
 */

declare(strict_types = 1);

/**
 * Implements hook_theme().
 */
function oe_content_event_event_programme_theme(): array {
  return [
    'event_programme' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function template_preprocess_event_programme(array &$variables) {
  oe_content_entity_default_preprocess($variables, 'event_programme');
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function oe_content_event_event_programme_theme_suggestions_event_programme(array $variables): array {
  return oe_content_entity_default_theme_suggestion($variables, 'event_programme');
}
