<?php

/**
 * @file
 * Install, update and uninstall functions.
 */

declare(strict_types = 1);

/**
 * Implements hook_install().
 */
function oe_content_skos_person_reference_install($is_syncing): void {
  if ($is_syncing) {
    return;
  }

  // Add 'EU political leader name' vocabulary.
  \Drupal::service('rdf_skos.skos_graph_configurator')->addGraphs([
    'political-leader' => 'http://publications.europa.eu/resource/dataset/political-leader',
  ]);
}
